// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var MapFreqencies = require("./MapFreqencies.bs.js");

var cmp = Caml_obj.caml_compare;

var FloatCmp = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

var deltas = MapFreqencies.mapFrequencies(/* () */0);

function processDeltas(_remaining, _currFreq, _seenFreqs) {
  while(true) {
    var seenFreqs = _seenFreqs;
    var currFreq = _currFreq;
    var remaining = _remaining;
    var match = Belt_Set.has(seenFreqs, currFreq);
    if (match) {
      return currFreq;
    } else if (remaining) {
      _seenFreqs = Belt_Set.add(seenFreqs, currFreq);
      _currFreq = currFreq + remaining[0];
      _remaining = remaining[1];
      continue ;
    } else {
      _remaining = deltas;
      continue ;
    }
  };
}

console.log(processDeltas(deltas, 0.0, Belt_Set.make(FloatCmp)).toString());

exports.FloatCmp = FloatCmp;
exports.deltas = deltas;
exports.processDeltas = processDeltas;
/* FloatCmp Not a pure module */
