// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var MapFreqencies = require("./MapFreqencies.bs.js");

console.log(Belt_List.reduce(MapFreqencies.mapFrequencies(/* () */0), 0.0, (function (prim, prim$1) {
            return prim + prim$1;
          })));

var frequency = /* () */0;

exports.frequency = frequency;
/*  Not a pure module */
