// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

console.log(Belt_Array.reduce(Belt_Array.map(Fs.readFileSync("input.txt", "utf8").split("\n"), (function (line) {
                var operator = line.substring(0, 1);
                var match = line.length > 1;
                var intValue = match ? Caml_format.caml_int_of_string(line.substring(1)) : 0;
                if (operator === "-") {
                  return Caml_int32.imul(intValue, -1);
                } else {
                  return intValue;
                }
              })), 0, (function (freq, value) {
            return value + freq | 0;
          })));

var foo = /* () */0;

exports.foo = foo;
/*  Not a pure module */
