// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

console.log($$Array.fold_left((function (freq, value) {
            return value + freq | 0;
          }), 0, $$Array.map((function (line) {
                var operator = line.substring(0, 1);
                var match = line.length > 1;
                var intValue = match ? Caml_format.caml_int_of_string(line.substring(1)) : 0;
                if (operator === "-") {
                  return Caml_int32.imul(intValue, -1);
                } else {
                  return intValue;
                }
              }), Fs.readFileSync("input.txt", "utf8").split("\n"))));

/*  Not a pure module */
