// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function mapFrequencies(param) {
  var match = typeof __dirname === "undefined" ? undefined : __dirname;
  var dirname = match !== undefined ? match : "";
  return Belt_List.map(Belt_List.fromArray(Fs.readFileSync(Path.join(dirname, "input.txt"), "utf8").split("\n")), (function (prim) {
                return Number(prim);
              }));
}

exports.mapFrequencies = mapFrequencies;
/* fs Not a pure module */
